framework:
    messenger:
        # Uncomment this (and the failed transport below) to send failed messages to this transport for later handling.
        # failure_transport: failed
        default_bus: command_bus
        buses:
            command_bus:
                default_middleware:
                    enabled: true
                    allow_no_handlers: false
                middleware:
                    - validation
                    #- doctrine_transaction
                    #- router_context
            query_bus:
                default_middleware:
                    enabled: true
                    allow_no_handlers: false
                middleware:
                    - validation
                    #- doctrine_transaction
                    #- router_context
            event_bus:
                default_middleware:
                    enabled: true
                    allow_no_handlers: true
                middleware:
                    - validation
                    #- doctrine_transaction
                    #- router_context
            shared_query_bus:
                default_middleware:
                    enabled: true
                    allow_no_handlers: false
                middleware:
                    - validation
                    #- doctrine_transaction
                    #- router_context
            shared_event_bus:
                default_middleware:
                    enabled: true
                    allow_no_handlers: true
                middleware:
                    - validation
                    #- doctrine_transaction
                    #- router_context
        transports:
            # https://symfony.com/doc/current/messenger.html#transport-configuration
            async: '%env(MESSENGER_TRANSPORT_DSN)%'
            failed: '%env(MESSENGER_TRANSPORT_DSN_FAILED)%'
            sync: 'sync://'
        routing:
        # Route your messages to the transports
        # 'App\Message\YourMessage': async

# when@test:
#    framework:
#        messenger:
#            transports:
#                # replace with your transport name here (e.g., my_transport: 'in-memory://')
#                # For more Messenger testing tools, see https://github.com/zenstruck/messenger-test
#                async: 'in-memory://'
